//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BindablePropertyAnalyzerAndCodeFix.Analyzer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AnalyzerResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AnalyzerResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BindablePropertyAnalyzerAndCodeFix.Analyzer.AnalyzerResources", typeof(AnalyzerResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class must be partial.
        /// </summary>
        public static string GLLBP001Description {
            get {
                return ResourceManager.GetString("GLLBP001Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class &apos;{0}&apos; contains generated code and must be declared as &apos;partial&apos;.
        /// </summary>
        public static string GLLBP001MessageFormat {
            get {
                return ResourceManager.GetString("GLLBP001MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class must be partial.
        /// </summary>
        public static string GLLBP001Title {
            get {
                return ResourceManager.GetString("GLLBP001Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple field names are ambiguous.
        /// </summary>
        public static string GLLBP002Description {
            get {
                return ResourceManager.GetString("GLLBP002Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field names after {0} are ambiguous.
        /// </summary>
        public static string GLLBP002MessageFormat {
            get {
                return ResourceManager.GetString("GLLBP002MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambiguous field names specified.
        /// </summary>
        public static string GLLBP002Title {
            get {
                return ResourceManager.GetString("GLLBP002Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument must be a Maui BindingMode value.
        /// </summary>
        public static string GLLBP003Description {
            get {
                return ResourceManager.GetString("GLLBP003Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument must be a valid BindingMode.
        /// </summary>
        public static string GLLBP003MessageFormat {
            get {
                return ResourceManager.GetString("GLLBP003MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid BindingMode.
        /// </summary>
        public static string GLLBP003Title {
            get {
                return ResourceManager.GetString("GLLBP003Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a valid BindableProperty argument.
        /// </summary>
        public static string GLLBP004Description {
            get {
                return ResourceManager.GetString("GLLBP004Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid argument.
        /// </summary>
        public static string GLLBP004MessageFormat {
            get {
                return ResourceManager.GetString("GLLBP004MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid argument.
        /// </summary>
        public static string GLLBP004Title {
            get {
                return ResourceManager.GetString("GLLBP004Title", resourceCulture);
            }
        }
    }
}
