//HintName: Test_All_Properties_BorderColor.g.cs
//  <auto-generated - BindablePropertyGenerator Version: 0.6.7.0-beta />
namespace UnitTest;

using Microsoft.Maui.Controls;
using Microsoft.Maui.Graphics;

public partial class Test_All_Properties
{
    public static new readonly BindableProperty BorderColorProperty
           = BindableProperty.Create( nameof(BorderColor),
                                      typeof(Color),
                                      typeof(ContentView),
                                      defaultBindingMode: BindingMode.OneTime,
                                      defaultValue: Colors.Red,
                                      validateValue: OnValidateBorderColor,
                                      propertyChanged: OnBorderColorChanged,
                                      propertyChanging: OnBorderColorChanging,
                                      coerceValue: OnCoerceBorderColorValue,
                                      defaultValueCreator: OnCreateDefaultBorderColorValue
                                    );
    public new Color BorderColor
    {
        get => (Color)GetValue( BorderColorProperty );
        set => SetValue( BorderColorProperty, value );
    }
}
