//HintName: Test_HidesBaseProperty_ExtraColor.g.cs
//  <auto-generated - BindablePropertyGenerator Version: 0.6.8.0-beta />
namespace UnitTest;

using Microsoft.Maui.Controls;
using Microsoft.Maui.Graphics;

public partial class Test_HidesBaseProperty
{
    public static readonly BindableProperty ExtraColorProperty
           = BindableProperty.Create( nameof(ExtraColor),
                                      typeof(Color),
                                      typeof(Test_HidesBaseProperty)
                                    );
    public Color ExtraColor
    {
        get => (Color)GetValue( ExtraColorProperty );
        set => SetValue( ExtraColorProperty, value );
    }
}
