//HintName: Test_DeclaringType_Override_BorderColor.g.cs
//  <auto-generated - BindablePropertyGenerator Version: 0.6.7.0-beta />
namespace UnitTest7;

using Microsoft.Maui.Controls;
using Microsoft.Maui.Graphics;

public partial class Test_DeclaringType_Override
{
    public static readonly BindableProperty BorderColorProperty
           = BindableProperty.Create( nameof(BorderColor),
                                      typeof(Color),
                                      typeof(Test_DeclaringType_Override),
                                      bindingMode: BindingMode.TwoWay
                                    );
    public Color BorderColor
    {
        get => (Color)GetValue( BorderColorProperty );
        set => SetValue( BorderColorProperty, value );
    }
}
