//HintName: Test_DefaultValue_BackDropColor1.g.cs
//  <auto-generated - BindablePropertyGenerator Version: 0.6.7.0-beta />
namespace UnitTest;

using Microsoft.Maui.Controls;
using Microsoft.Maui.Graphics;

public partial class Test_DefaultValue
{
    public static readonly BindableProperty BackDropColor1Property
           = BindableProperty.Create( nameof(BackDropColor1),
                                      typeof(Color),
                                      typeof(Test_DefaultValue),
                                      defaultValue: Colors.Green
                                    );
    public Color BackDropColor1
    {
        get => (Color)GetValue( BackDropColor1Property );
        set => SetValue( BackDropColor1Property, value );
    }
}
