//HintName: Test_Inline_Nested_Namespace_TextColor.g.cs
//  <auto-generated - BindablePropertyGenerator Version: 0.6.7.0-beta />

using Microsoft.Maui.Controls;
using Microsoft.Maui.Graphics;

namespace UnitTest.UnitTestInner
{
    public partial class Test_Inline_Nested_Namespace
    {
        public static readonly BindableProperty TextColorProperty
               = BindableProperty.Create( nameof(TextColor),
                                          typeof(Color),
                                          typeof(Test_Inline_Nested_Namespace)
                                        );
        public Color TextColor
        {
            get => (Color)GetValue( TextColorProperty );
            set => SetValue( TextColorProperty, value );
        }
    }
}
