//HintName: Test_DefaultValue_BackDropColor2.g.cs
//  <auto-generated - BindablePropertyGenerator Version: 0.6.7.0-beta />
namespace UnitTest;

using Microsoft.Maui.Controls;
using Microsoft.Maui.Graphics;

public partial class Test_DefaultValue
{
    public static readonly BindableProperty BackDropColor2Property
           = BindableProperty.Create( nameof(BackDropColor2),
                                      typeof(Color),
                                      typeof(Test_DefaultValue),
                                      defaultValue: Color.FromArgb("#4B000000")
                                    );
    public Color BackDropColor2
    {
        get => (Color)GetValue( BackDropColor2Property );
        set => SetValue( BackDropColor2Property, value );
    }
}
