//HintName: Test_CoerceValue_BorderColor.g.cs
//  <auto-generated - BindablePropertyGenerator Version: 0.6.7.0-beta />
namespace UnitTest;

using Microsoft.Maui.Controls;
using Microsoft.Maui.Graphics;

public partial class Test_CoerceValue
{
    public static readonly BindableProperty BorderColorProperty
           = BindableProperty.Create( nameof(BorderColor),
                                      typeof(Color),
                                      typeof(Test_CoerceValue),
                                      coerceValue: OnCoerceBorderColorValue
                                    );
    public Color BorderColor
    {
        get => (Color)GetValue( BorderColorProperty );
        set => SetValue( BorderColorProperty, value );
    }
}
